name: badgers_search
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # core
  - python=3.10
  - pip
  - numpy=1.23
  - scipy=1.15
  - pandas=2.3
  - matplotlib=3.10
  - seaborn=0.13
  - openpyxl
  - biopython=1.85
  - editdistance
  - adapt=1.6.0



  - pip:
      - flexs
      - fastaparser==1.1
      #- keras==2.15.0
      #- tensorflow[and-cuda]

